# Form implementation generated from reading ui file 'grade_gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 550)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Student_name_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Student_name_input.setGeometry(QtCore.QRect(270, 40, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Student_name_input.setFont(font)
        self.Student_name_input.setObjectName("Student_name_input")
        self.Student_Name_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Student_Name_text.setGeometry(QtCore.QRect(39, 40, 201, 40))
        self.Student_Name_text.setObjectName("Student_Name_text")
        self.Number_of_attempts_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Number_of_attempts_input.setGeometry(QtCore.QRect(270, 100, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Number_of_attempts_input.setFont(font)
        self.Number_of_attempts_input.setObjectName("Number_of_attempts_input")
        self.number_of_attempts_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.number_of_attempts_text.setGeometry(QtCore.QRect(39, 100, 201, 40))
        self.number_of_attempts_text.setObjectName("number_of_attempts_text")
        self.Score_one_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Score_one_input.setGeometry(QtCore.QRect(270, 170, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Score_one_input.setFont(font)
        self.Score_one_input.setObjectName("Score_one_input")
        self.score_one_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.score_one_text.setGeometry(QtCore.QRect(80, 170, 170, 40))
        self.score_one_text.setObjectName("score_one_text")
        self.score_two_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.score_two_text.setGeometry(QtCore.QRect(80, 230, 170, 40))
        self.score_two_text.setObjectName("score_two_text")
        self.score_two_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_two_input.setGeometry(QtCore.QRect(270, 230, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.score_two_input.setFont(font)
        self.score_two_input.setObjectName("score_two_input")
        self.score_three_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_three_input.setGeometry(QtCore.QRect(270, 290, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.score_three_input.setFont(font)
        self.score_three_input.setObjectName("score_three_input")
        self.score_three_text_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.score_three_text_2.setGeometry(QtCore.QRect(80, 290, 170, 40))
        self.score_three_text_2.setObjectName("score_three_text_2")
        self.score_four_input_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.score_four_input_2.setGeometry(QtCore.QRect(270, 350, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.score_four_input_2.setFont(font)
        self.score_four_input_2.setObjectName("score_four_input_2")
        self.score_four_text_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.score_four_text_3.setGeometry(QtCore.QRect(80, 350, 170, 40))
        self.score_four_text_3.setObjectName("score_four_text_3")
        self.submit_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_Button.setGeometry(QtCore.QRect(210, 400, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.submit_Button.setFont(font)
        self.submit_Button.setObjectName("submit_Button")
        self.enter_student_name_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.enter_student_name_text.setGeometry(QtCore.QRect(160, 450, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_student_name_text.setFont(font)
        self.enter_student_name_text.setObjectName("enter_student_name_text")
        self.enter_valid_number_of_attempts_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.enter_valid_number_of_attempts_text.setGeometry(QtCore.QRect(160, 450, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_valid_number_of_attempts_text.setFont(font)
        self.enter_valid_number_of_attempts_text.setObjectName("enter_valid_number_of_attempts_text")
        self.enter_valid_score_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.enter_valid_score_text.setGeometry(QtCore.QRect(160, 450, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.enter_valid_score_text.setFont(font)
        self.enter_valid_score_text.setObjectName("enter_valid_score_text")
        self.Grades_submmitted_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Grades_submmitted_text.setGeometry(QtCore.QRect(160, 450, 280, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Grades_submmitted_text.setFont(font)
        self.Grades_submmitted_text.setObjectName("Grades_submmitted_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Student_Name_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Student Name:</span></p></body></html>"))
        self.number_of_attempts_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Number of attempts:</span></p></body></html>"))
        self.score_one_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Score 1:</span></p></body></html>"))
        self.score_two_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Score 2:</span></p></body></html>"))
        self.score_three_text_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Score 3:</span></p></body></html>"))
        self.score_four_text_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Score 4:</span></p></body></html>"))
        self.submit_Button.setText(_translate("MainWindow", "SUBMIT"))
        self.enter_student_name_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ff0000;\">Enter Student Name</span></p></body></html>"))
        self.enter_valid_number_of_attempts_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; color:#ff0000;\">Enter valid number of attempts (1-4)</span></p></body></html>"))
        self.enter_valid_score_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">Enter Valid Score (1-100)</span></p></body></html>"))
        self.Grades_submmitted_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00aa00;\">Grades Submitted</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
