# Form implementation generated from reading ui file 'Votegui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoteWindow(object):
    def setupUi(self, VoteWindow):
        VoteWindow.setObjectName("VoteWindow")
        VoteWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        VoteWindow.setEnabled(True)
        VoteWindow.resize(520, 500)
        self.centralwidget = QtWidgets.QWidget(parent=VoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.JohnButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.JohnButton.setGeometry(QtCore.QRect(210, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.JohnButton.setFont(font)
        self.JohnButton.setIconSize(QtCore.QSize(50, 50))
        self.JohnButton.setObjectName("JohnButton")
        self.JaneButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.JaneButton.setGeometry(QtCore.QRect(210, 200, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.JaneButton.setFont(font)
        self.JaneButton.setAutoExclusive(True)
        self.JaneButton.setObjectName("JaneButton")
        self.IDinput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDinput.setGeometry(QtCore.QRect(205, 80, 225, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IDinput.setFont(font)
        self.IDinput.setObjectName("IDinput")
        self.IdText = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.IdText.setGeometry(QtCore.QRect(80, 80, 100, 40))
        self.IdText.setObjectName("IdText")
        self.VotingApplication = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.VotingApplication.setGeometry(QtCore.QRect(80, 0, 350, 50))
        self.VotingApplication.setObjectName("VotingApplication")
        self.Candidates = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Candidates.setGeometry(QtCore.QRect(130, 150, 250, 40))
        self.Candidates.setObjectName("Candidates")
        self.SubmitVote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitVote.setGeometry(QtCore.QRect(145, 330, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SubmitVote.setFont(font)
        self.SubmitVote.setAcceptDrops(False)
        self.SubmitVote.setObjectName("SubmitVote")
        self.AlreadyVotedText = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.AlreadyVotedText.setGeometry(QtCore.QRect(180, 380, 159, 40))
        self.AlreadyVotedText.setObjectName("AlreadyVotedText")
        self.Vali_id_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Vali_id_text.setGeometry(QtCore.QRect(142, 380, 225, 40))
        self.Vali_id_text.setObjectName("Vali_id_text")
        self.Vote_submitted_txt = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Vote_submitted_txt.setGeometry(QtCore.QRect(155, 380, 200, 40))
        self.Vote_submitted_txt.setObjectName("Vote_submitted_txt")
        self.Select_candidate_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Select_candidate_text.setGeometry(QtCore.QRect(142, 380, 225, 40))
        self.Select_candidate_text.setObjectName("Select_candidate_text")
        VoteWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VoteWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 26))
        self.menubar.setObjectName("menubar")
        VoteWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VoteWindow)
        self.statusbar.setObjectName("statusbar")
        VoteWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VoteWindow)
        QtCore.QMetaObject.connectSlotsByName(VoteWindow)

    def retranslateUi(self, VoteWindow):
        _translate = QtCore.QCoreApplication.translate
        VoteWindow.setWindowTitle(_translate("VoteWindow", "MainWindow"))
        self.JohnButton.setText(_translate("VoteWindow", "John"))
        self.JaneButton.setText(_translate("VoteWindow", "Jane"))
        self.IdText.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">ID</span></p></body></html>"))
        self.VotingApplication.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">VOTING APPLICATION</span></p></body></html>"))
        self.Candidates.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">CANDIDATES</span></p></body></html>"))
        self.SubmitVote.setText(_translate("VoteWindow", "SUBMIT VOTE"))
        self.AlreadyVotedText.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ff0000;\">Already Voted</span></p></body></html>"))
        self.Vali_id_text.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ff0000;\">Enter Valid 8-digit Voter ID</span></p></body></html>"))
        self.Vote_submitted_txt.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#00aa00;\">Voted Submitted</span></p></body></html>"))
        self.Select_candidate_text.setHtml(_translate("VoteWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; color:#ff0000;\">Select A Candidate</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoteWindow = QtWidgets.QMainWindow()
    ui = Ui_VoteWindow()
    ui.setupUi(VoteWindow)
    VoteWindow.show()
    sys.exit(app.exec())
